# Generated by Django 3.1.4 on 2021-01-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210104_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='posts_following',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
