# Generated by Django 3.1.4 on 2021-01-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210112_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='num_of_comments',
        ),
    ]
