# Generated by Django 3.1.4 on 2021-01-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_post_num_of_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_following',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
