name: Network CI

on:
  push:
    branches: [ main ]

jobs:
  test_network:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        pip install django
        pip install django_restframework
    - name: Run Tests
      run: |
        python manage.py test
